export const seedPrizes = [
  {
    id: 3501,
    title: "Скидка 800 ₽ на первый заказ отеля от 15 000 ₽",
    category: "Отели",
    promoCodeType: "Промокод на повторный заказ",
    type: "Приз",
    hasPrizeLimit: true,
    promoCodesFileName: "hotels-repeat.csv",
    promoCodes: ["HOTEL-800-001", "HOTEL-800-002", "HOTEL-800-003"],
    promoCodeValue: "",
    totalCount: 800,
    remainingCount: 215,
    chanceValue: "1x",
    hasUserLimit: true,
    userLimitCount: 1,
    activeFrom: "2026-05-01",
    activeTo: "2026-08-31",
    rouletteImage: {
      name: "case-yellow.webp",
      previewUrl: "/game/bags/case.webp"
    },
    myPrizeText: "Скидка 800 ₽",
    rouletteDescription: "Скидка 800 ₽ на повторный заказ отеля от 15 000 ₽"
  },
  {
    id: 3502,
    title: "Скидка 300 ₽ на заказ отеля от 5 000 ₽",
    category: "Отели",
    promoCodeType: "Промокод на первый заказ",
    type: "Приз",
    hasPrizeLimit: true,
    promoCodesFileName: "hotels-first.csv",
    promoCodes: ["HOTEL-300-001", "HOTEL-300-002", "HOTEL-300-003"],
    promoCodeValue: "",
    totalCount: 1500,
    remainingCount: 910,
    chanceValue: "1x",
    hasUserLimit: true,
    userLimitCount: 1,
    activeFrom: "2026-05-01",
    activeTo: "2026-08-31",
    rouletteImage: {
      name: "case-pink.webp",
      previewUrl: "/game/bags/case2.webp"
    },
    myPrizeText: "Скидка 300 ₽",
    rouletteDescription: "Скидка 300 ₽ на первый заказ отеля от 5 000 ₽"
  },
  {
    id: 3503,
    title: "Скидка 800 ₽ на первый заказ авиа от 15 000 ₽",
    category: "Авиа",
    promoCodeType: "Промокод на первый заказ",
    type: "Приз",
    hasPrizeLimit: true,
    promoCodesFileName: "avia-first.csv",
    promoCodes: ["AVIA-800-001", "AVIA-800-002", "AVIA-800-003"],
    promoCodeValue: "",
    totalCount: 950,
    remainingCount: 264,
    chanceValue: "1x",
    hasUserLimit: true,
    userLimitCount: 1,
    activeFrom: "2026-05-01",
    activeTo: "2026-08-31",
    rouletteImage: {
      name: "case-green.webp",
      previewUrl: "/game/bags/case3.webp"
    },
    myPrizeText: "Скидка 800 ₽",
    rouletteDescription: "Скидка 800 ₽ на первый заказ авиа от 15 000 ₽"
  },
  {
    id: 3504,
    title: "Скидка 300 ₽ на заказ авиа от 15 000 ₽",
    category: "Авиа",
    promoCodeType: "Промокод на повторный заказ",
    type: "Приз",
    hasPrizeLimit: false,
    promoCodesFileName: "",
    promoCodes: [],
    promoCodeValue: "AVIA-UNLIM-300",
    totalCount: 0,
    remainingCount: 0,
    chanceValue: "1x",
    hasUserLimit: false,
    userLimitCount: 0,
    activeFrom: "2026-05-01",
    activeTo: "2026-08-31",
    rouletteImage: {
      name: "case-blue.webp",
      previewUrl: "/game/bags/case4.webp"
    },
    myPrizeText: "Скидка 300 ₽",
    rouletteDescription: "Скидка 300 ₽ на повторный заказ авиа без общего лимита призов"
  },
  {
    id: 3505,
    title: "1 000 баллов Ozon",
    category: "",
    promoCodeType: "",
    type: "Не приз",
    hasPrizeLimit: false,
    promoCodesFileName: "",
    promoCodes: [],
    promoCodeValue: "",
    totalCount: 0,
    remainingCount: 0,
    chanceValue: "1x",
    hasUserLimit: false,
    userLimitCount: 0,
    activeFrom: "2026-05-01",
    activeTo: "2026-06-30",
    rouletteImage: {
      name: "case-colorful.webp",
      previewUrl: "/game/bags/case5.webp"
    },
    myPrizeText: "1 000 баллов Ozon",
    rouletteDescription: "Начисление 1 000 баллов Ozon"
  },
  {
    id: 3506,
    title: "300 миль",
    category: "",
    promoCodeType: "",
    type: "Не приз",
    hasPrizeLimit: false,
    promoCodesFileName: "",
    promoCodes: [],
    promoCodeValue: "",
    totalCount: 0,
    remainingCount: 0,
    chanceValue: "1x",
    hasUserLimit: false,
    userLimitCount: 0,
    activeFrom: "2026-05-01",
    activeTo: "2026-06-30",
    rouletteImage: {
      name: "case-violet.webp",
      previewUrl: "/game/bags/case2.webp"
    },
    myPrizeText: "300 миль",
    rouletteDescription: "Начисление 300 миль"
  }
];
